### ISSUE TITLE
Conteos Portal de datos

### ISSUE THREAD

**Issue by leobuitrago** [SIB-Colombia/portal-de-datos-frontend#101]
Los llamados de conteo de registros en el home del Portal de Datos empleando el API de GBIF son los siguientes:

**REGISTROS**: http://api.gbif.org/v1/occurrence/count?country=CO&publishingCountry=CO

**CON COORDENADAS**: http://api.gbif.org/v1/occurrence/count?country=CO&isGeoreferenced=true&publishingCountry=CO

**ESPECIES**: El conteo de especies en GBIF no está comprendido dentro de los parámetros de búsqueda en el API. Esta cifra depende totalmente en este momento de nuestro propio indexador y podría extraerse de un conteo único de los valores en los registros que tengan información tanto en el campo DwC genus como en campo specificEpithet

**Comment by camiplata** [comment]
Este issue se cierra por ser duplicado de #166
@leobuitrago hacer las aclaraciones pertinentes sobre el origen de las cifras en el  issue #166
