### ISSUE TITLE
Capas independientes - Explorador Geográfico

### ISSUE THREAD

**Issue by leobuitrago** [SIB-Colombia/portal-de-datos-frontend#102]
Departamentos de Colombia: 1 capa convertida en 33 independientes
[DESCARGAR CAPAS](https://drive.google.com/file/d/1Th4ke-yXSds9XElXbflKCPGAeqUOLejh/view?usp=sharing)

**Comment by camiplata** [comment]
@RicardoOrtizG revisar si las capas fueron incorporadas exitosamente

**Comment by RicardoOrtizG** [comment]
El despliegue de la capa por departamento en el explorador gegoráfico funciona correctamente
