### ISSUE TITLE
Nueva disposición de elementos en barra de cifras estadísticas de la pantalla de inicio

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#103]
PNG: 
![barra-estadisticas-home.png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/96e71487-b0ab-4113-9528-8871a3a815b1)

PDF:
[https://app.zenhub.com/files/81233273/e5b45cd9-1ef1-4f87-a37f-53ffef451d83/download](https://app.zenhub.com/files/81233273/e5b45cd9-1ef1-4f87-a37f-53ffef451d83/download)

**Comment by javiesgm** [comment]
@jag2kn  Esto aplicaría para todos los canales de participación

**Comment by jag2kn** [comment]
entendido
