### ISSUE TITLE
Nombre científico Página Registro Biológico

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/portal-de-datos-frontend#111]
El nombre científico principal de la página del registro biológico debe aparecer en letra cursiva, ver mockup issue #61.

Vista Actual
![image](https://user-images.githubusercontent.com/5700527/37737820-fed9a534-2d22-11e8-9ce0-681aefe8e37c.png)

**Comment by jag2kn** [comment]
Hecho

**Comment by dapino** [comment]
@jag2kn  El nombre científico principal de la página del registro biológico sigue estando sin cursiva
