### ISSUE TITLE
Cifras Página de publicador

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/portal-de-datos-frontend#112]
Aplica el el mismo issue #111 de la página del recurso, sobra la cifra de especies

@javiesgm tenemos un mockup que podamos asociar?
@leobuitrago es válido este issue o ya esta resuelta la consulta de especies (no taxones) únicos de acuerto a tu issue #101?

Versión actual con cifra de especies sobrante
![image](https://user-images.githubusercontent.com/5700527/37738803-242bd0de-2d26-11e8-8458-f1df2762994e.png)

**Comment by johnfra797** [comment]
Listo

**Comment by dapino** [comment]
Revisar mockup

**Comment by camiplata** [comment]
Se cierra por ser duplicado del issue #166
