### ISSUE TITLE
Minúsculas sostenidas en los filtros del explorador

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos-frontend#115]
En el explorador geográfico en todos los filtros están apareciendo las opciones en minúsculas sostenidas. 

![image](https://user-images.githubusercontent.com/15789737/38375678-63e96d5c-38bc-11e8-800f-08a8a6081a0d.png)

**Comment by jag2kn** [comment]
Hecho
