### ISSUE TITLE
Opción "undefined" en los filtros de búsqueda

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos-frontend#116]
En los filtros de búsqueda aparece una opción "undefined" con un número de registros asociados que varía en cada filtro, pero que cuando logra desplegar los resultados esta vacío. 

![image](https://user-images.githubusercontent.com/15789737/38376017-3c78f43a-38bd-11e8-9386-c1b676b12315.png)

**Comment by jag2kn** [comment]
Hecho

**Comment by dapino** [comment]
@jag2kn Cómo se resolvió? puede volver a aparecer cuando se haga la indexación completa?
