### ISSUE TITLE
Cifras página de inicio portal de datos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#117]
@jag2kn 
Ajustar las categorías de las cifras según mockup - Poner: #Registros - #Recursos - #Publicadores en vez de #Registros - #Con coordenadas - #Especies

![Datos-home-cifras-destacadas.png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/ff7caf21-7018-4c77-a64f-f74fb7289d78)

**Comment by johnfra797** [comment]
Si la llamada es esta http://75.126.129.179:5100/api/statitics/get

retorna

{
      "name": "ESPECÍMENES",
      "value": 62322
    },
    {
      "name": "COLECCIONES ",
      "value": 15
    },
    {
      "name": "PUBLICADORES",
      "value": 7
    }

Actualmente la llamada es

http://75.126.129.179:5100/api/statitics/get?keyType=occurrence&keyType=specimen

{
      "name": "REGISTROS",
      "value": 139573
    },
    {
      "name": "PUBLICADORES",
      "value": 5
    }

**Comment by dapino** [comment]
@jag2kn la fuente del título debe ser de 12px

**Comment by camiplata** [comment]
El tema de las cifras está resuelto. 
@dapino creo que el tema de la fuente falta por ser resuelto, por favor confirmar.
![image](https://user-images.githubusercontent.com/5700527/42644231-ada86da2-85c0-11e8-9aa8-7a805c5c92a2.png)
