### ISSUE TITLE
Detalle de registro	Revisar y ajustar proporciones según mockups

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#126]
Detalle de registro	Revisar y ajustar proporciones según mockups

**Comment by dapino** [comment]
@jag2kn Ajustes principalmente de espaciado, el título del ID, etc


![captura de pantalla 2018-05-09 a la s 11 22 30 a m 2](https://user-images.githubusercontent.com/11689269/40790716-39cf0114-64bb-11e8-8d63-4c72c0a26e35.png)
