### ISSUE TITLE
Detalle de registro	Incluir "ID del registro"

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#127]
Detalle de registro	Incluir "ID del registro"

**Comment by dapino** [comment]
![screen shot 2018-05-30 at 4 02 50 pm](https://user-images.githubusercontent.com/11689269/40747438-ee25a6d4-6422-11e8-8164-f808da1135ee.png)

Antes del id debe decir "ID DEL REGISTRO:" cómo en el mockup:

![captura de pantalla 2018-05-09 a la s 11 22 30 a m](https://user-images.githubusercontent.com/11689269/40747500-17fa7fd4-6423-11e8-980e-71f5e90cb7df.png)

**Comment by camiplata** [comment]
El issue no esta resuelto, aún falta hacer el ajuste indicado en el comentario anterior.

**Comment by dapino** [comment]
El issue se resolvió
