### ISSUE TITLE
Explorador Geográfico	Dibujar en el mapa no va ahí

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#142]
Explorador Geográfico	Dibujar en el mapa no va ahí y si no funciona, mejor retirarlo.

**Comment by camiplata** [comment]
No es claro el issue.
@leobuitrago @RicardoOrtizG  Finalmente que va a pasar con la función de 'dibujar'?

**Comment by javiesgm** [comment]
@camiplata esto va para FASE 2. Por fa genera un issue nuevo y cerramos este.

**Comment by camiplata** [comment]
Duplicado de #195
