### ISSUE TITLE
Filtros - Búsqueda por recurso	Filtro por publicador no funciona

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#145]
Filtros - Búsqueda por recurso	Filtro por publicador no funciona

**Comment by dapino** [comment]
Funciona para FIMA, pero el número en el filtro, no es claro que se refiere a los registros 
![screen shot 2018-05-30 at 3 17 30 pm](https://user-images.githubusercontent.com/11689269/40745332-cc065e28-641c-11e8-8568-a3e707a7c2bb.png)

**Comment by camiplata** [comment]
La cifra fue eliminada por completo
