### ISSUE TITLE
Página de publicador	Alinear #REGISTROS y #RECURSOS según mockup

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#149]
Página de publicador	Alinear #REGISTROS y #RECURSOS según mockup

**Comment by dapino** [comment]
![captura de pantalla 2018-05-09 a la s 12 19 00 p m](https://user-images.githubusercontent.com/11689269/40791587-732f0358-64bd-11e8-9847-d2c0c2c97912.png)

**Comment by camiplata** [comment]
Se cierra este issue, este tema se trata en detalle en el issue #166,
