### ISSUE TITLE
Detalle de recurso	"Cifras en la página inicial de detalle de recurso  ""REGISTROS"" y ""CON COORDENADAS"""

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#151]
Detalle de recurso	"Cifras en la página inicial de detalle de recurso: NO VAN ""Family"" - ""Genus"" - ""Specie"" - 
Van como en el mockup que incluyo. Van solo ""REGISTROS"" y ""CON COORDENADAS"""

**Comment by johnfra797** [comment]
Listo

**Comment by dapino** [comment]
@jag2kn Seguir lineamiento del mockup, las cifras van centradas, no ocupando cada una el 50% y el título de las cifras "registro"y "con coordenadas"debe ir más pequeño al igual que en el home.

![captura de pantalla 2018-05-09 a la s 12 25 07 p m](https://user-images.githubusercontent.com/11689269/40749704-7d9bca1c-642a-11e8-8c8d-6008bbdf2c90.png)

**Comment by camiplata** [comment]
Se cierra este issue, este tema se trata en detalle en el issue #166,
