### ISSUE TITLE
Palabras clave. Filtro 'Redes y Proyectos'

### ISSUE THREAD

**Issue by leobuitrago** [SIB-Colombia/portal-de-datos-frontend#161]
En esta tabla se encuentran las palabras clave por las cuales se debe hacer búsqueda en el eml para generar el filtro **Redes y proyectos**

Palabra clave | Nombre del Filtro
-- | --
RNOA | Red Nacional Observadores de Aves
VALLE_DEL_CAUCA | Datos de Biodiversidad Valle del Cauca
SIB_MARINO | Sistema de Información sobre Biodiversidad Marina
RESNATUR | Asociación Red Colombiana de Reservas Naturales de la Sociedad Civil
RNJB | Red Nacional de Jardines Botánicos de Colombia
COLOMBIA_BIO | Colombia BIO
BST | Bosque Seco Tropical
IFN | Inventario Forestal Nacional
SIRAP-EC | Sistemas Regional de Áreas Protegidas del Eje Cafetero

**Comment by camiplata** [comment]
El issue esta resuelto @leobuitrago debemos tener claro como podemos ir actualizando las categorias que van en este filtro.
