### ISSUE TITLE
DETALLE DEL RECURSO | Bug en la sección partes asociadas

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos-frontend#182]
En algunos conjuntos de datos, particularmente en  Dataves en la sección Partes asociadas, aparece al inicio de cada proveedor la etiqueta 'undefined'.

![image](https://user-images.githubusercontent.com/15789737/42350398-f96f7ac8-8075-11e8-815f-ea166c4cb5d3.png)

**Comment by jag2kn** [comment]
Hecho
