### ISSUE TITLE
FILTRO SUPERIOR | Filtro por proyectos: Colombia BIO sin resultados

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/portal-de-datos-frontend#208]
El filtro por proyectos: la opción Colombia BIO no genera resultados. Hay que revisar si la etiqueta ya se incorporó en las palabras clave de los recursos del proyecto o si el filtro se genera a partir del título del recurso, deberían haber resultados.

@leobuitrago  @camiplata  Tener en cuenta para la próxima indexación.

En algunos recursos la palabra clave está en el Tesauro de GBIF
![image](https://user-images.githubusercontent.com/15789737/48586841-10be1f80-e8ff-11e8-880b-ea7f26b8e03c.png)

**Comment by RicardoOrtizG** [comment]
Si hay resultados por proyecto Colombia BIO en el filtro lateral  de Redes y Proyectos.
![image](https://user-images.githubusercontent.com/15789737/48626010-c54b5600-e97e-11e8-8c95-b7a7d5a3ee2c.png)

**Comment by iraida07** [comment]
Si hay resultados, entonces se cierra el issue
