### ISSUE TITLE
Filtros Definitivos para Búsqueda por registros 

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#55]
Adjunto montaje definitivo de filtros para Portal de datos
[Filtros.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1231952/Filtros.pdf)

En el archivo están los filtros definitivos en diferentes estados: 
![filtros-def](https://user-images.githubusercontent.com/14220404/29423109-1d8b60e0-8340-11e7-9403-9246dbac1b6c.png)

Y los tipos de filtros: 
![tipo de filtros](https://user-images.githubusercontent.com/14220404/29423115-235fc740-8340-11e7-9b26-a4aad8533afd.png)

Este es el archivo con las equivalencias en DwC:
https://docs.google.com/spreadsheets/d/1g1O8D9iFyIjWbLnDWFb-_V35yplciSknj7_uFhwTiro/edit#gid=2098039901

Para los comportamientos de cada filtro adjunto unos GIF's de referencia: 
- Texto abierto: 
![filtro-campo de texto abierto](https://user-images.githubusercontent.com/14220404/29423203-7ebbb090-8340-11e7-8823-5441374654f8.gif)

- Lista de selección + Texto abierto + lista Top 10 checkbox: 
![filtro-taxonomia](https://user-images.githubusercontent.com/14220404/29423275-bc44dbbc-8340-11e7-8e4f-06b0a2670bcf.gif)
![filtro-ubicacion](https://user-images.githubusercontent.com/14220404/29423276-bc4632b4-8340-11e7-9a05-9e1bc4fa800f.gif)

- Fecha:
![filtro-fecha del evento](https://user-images.githubusercontent.com/14220404/29423319-e1730472-8340-11e7-81f4-eaddb461dcfa.gif)

- Checkbox: 
![filtro-licencias](https://user-images.githubusercontent.com/14220404/29423336-f14dcd96-8340-11e7-9087-a384a7ad6f1a.gif)

- Intervalo: 
![filtro-profundidad-intervalo](https://user-images.githubusercontent.com/14220404/29423349-fe46c50c-8340-11e7-9859-fe7be09e9d33.gif)

**Comment by cosmicgarden** [comment]
@jag2kn por favor revisar este issue https://github.com/SIB-Colombia/dataportal_v2_API/issues/1

**Comment by javiesgm** [comment]
@jag2kn  Por favor incluir un nuevo filtro: Multimedia (Tipo checkbox) 
Debe ir justo antes de licencia.

**Comment by jag2kn** [comment]
Se desplegaron avances en frontend, estamos trabajando en la conexión con las diferentes APIs

**Comment by jag2kn** [comment]
Se realizaron avances: https://github.com/SIB-Colombia/dataportal_v2_frontend/issues/78#issuecomment-352226247

**Comment by camiplata** [comment]
Falta implementar los siguientes filtros laterales:
Elevación
Profundidad
Fecha del Evento

**Comment by javiesgm** [comment]
@camiplata, esos filtros van a Fase 2. Es necesario crear un issue para cada uno con ese milestone. Tak tak.

**Comment by camiplata** [comment]
Se crearon Issues puntuales para cada filtro faltante #191 #192 #193 y se cierra el presente
