### ISSUE TITLE
Filtros - Búsqueda por RECURSOS

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#57]
Filtros definitivos para búsqueda por RECURSOS

[Filtros-recursos.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1234881/Filtros-recursos.pdf)

**Comment by camiplata** [comment]
Falta el filtro de fecha de publicación

**Comment by javiesgm** [comment]
@camiplata Filtro de fecha amerita issue independiente.

**Comment by camiplata** [comment]
Se genera un issue independiente #194  para el filtro faltante y se cierra el presente
