### ISSUE TITLE
Filtros Explorador Geográfico

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#59]
Filtros para explorador geográfico: 

Mockups: 
[Filtros-Explorador-Geografico.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1235434/Filtros-Explorador-Geografico.pdf)

**Comment by javiesgm** [comment]
Actualización de filtros para explorador Geográfico !

Incluímos el filtro por taxonomía como se acordó en la última sesión de trabajo: 

IMG: 
![filtros-explorador-geografico](https://user-images.githubusercontent.com/14220404/29620910-e591c194-87e4-11e7-9022-45d62d5b1a69.png)

PDF:
[Filtros-Explorador-Geografico.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1245731/Filtros-Explorador-Geografico.pdf)

**Comment by javiesgm** [comment]
Actualización de filtros #2 

Incluimos el filtro que permite dibujar polígonos en los mockups:

PDF: 
[Filtros-Exp-geo.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1252446/Filtros-Exp-geo.pdf)

IMG:
![filtros-explorador](https://user-images.githubusercontent.com/14220404/29723567-b0682448-898a-11e7-9185-3692d8f6d719.png)

**Comment by camiplata** [comment]
Se cierra por ser un duplicado del Issue #114 donde se dan indicaciones actualizadas respecto a los filtros del explorador.
