### ISSUE TITLE
Comportamiento especial para FILTRO Ubicación - Explorador geográfico

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#66]
@jag2kn 
Adjunto mockup del comportamiento del filtro "Ubicación" dentro del explorador geográfico. La idea es que cuando se seleccione país, solamente aparezcan dos opciones en checkbox: 
1. Colombia.
2. En otros países. 

IMG:
![filtros-explorador-pais](https://user-images.githubusercontent.com/14220404/29723646-06409044-898b-11e7-990d-5dc2faed147c.png)

**Comment by camiplata** [comment]
@jag2kn El filtro de Ubicación >país no está mostrando las opciones indicadas.
Se queda solo en país:
![image](https://user-images.githubusercontent.com/5700527/42640563-3361fb74-85b8-11e8-8dd4-ec6607fdd920.png)

@javiesgm Este sigue siendo el comportamiento deseado? o ha cambiado desde que se abrió el issue?

**Comment by camiplata** [comment]
Este issue se cierra ya que el tema se aclara en detalle en el issue #114
