### ISSUE TITLE
Filtros laterales funcionales

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#78]

**Comment by jag2kn** [comment]
Avances:

 * Se implementaron ya todos los componentes desde el frontend
 * Se tiene implementado el servicio con gbif para poblar algunos filtros http://beta.datos.biodiversidad.co/api/biological/filters
 * Se poblaron los filtros
  1. Licencias
  2. Base del registro
  3. Publicador

![base](https://user-images.githubusercontent.com/321637/34075954-97de0bee-e2a5-11e7-8d4f-2a9f34a0582e.png)
![licencia](https://user-images.githubusercontent.com/321637/34075955-97fbfc44-e2a5-11e7-9cb2-db8f648838e9.png)
![publicador](https://user-images.githubusercontent.com/321637/34075956-98163460-e2a5-11e7-8bcd-52e5f1faeef4.png)

http://beta.datos.biodiversidad.co/search
