### ISSUE TITLE
Error en la consulta al API de GBIF - Datos Colombia

### ISSUE THREAD

**Issue by leobuitrago** [SIB-Colombia/portal-de-datos-frontend#94]
El parámetro de búsqueda para todos los filtros en el portal y los demás canales dependientes de este debe tener agregado "**search?publishing_country=CO**" (ej. para plantas [http://beta.datos.biodiversidad.co/search?publishing_country=CO&taxon_key=6](http://beta.datos.biodiversidad.co/search?publishing_country=CO&taxon_key=6)). GBIF también agrega el parámetro "**&advanced=1**" al final pero no se si es necesario para la consulta , de momento veo que funciona sin agregarle eso.

**Comment by jag2kn** [comment]
Saludos el parámetro de búsqueda aunque no se ve en la URL el internamente agrega este parametro al enviar la consulta a gbif

Esto puede verse en firebug

![colombia](https://user-images.githubusercontent.com/321637/34062328-0930d606-e1ba-11e7-9e4d-172b02d3bbd3.png)

Los servicios que apuntan al api interna desde el servidor también se agrega ese parámetro.

**Comment by leobuitrago** [comment]
El parámetro es diferente al que estoy mencionando "publishing_country=CO no es lo mismo que "country=CO". Todas las consultas aún trae resultados de organizaciones NO colombianas (ej. iNaturalist)
<img width="1116" alt="captura de pantalla 2017-12-19 a la s 9 52 18 a m" src="https://user-images.githubusercontent.com/7794970/34163254-3f4a04d2-e4a4-11e7-8c69-a7a513574221.png">

**Comment by jag2kn** [comment]
Fue colocado el parametro publishing_country por favor confirmar

**Comment by jag2kn** [comment]
http://beta.datos.biodiversidad.co/search?taxon_key=6

**Comment by jag2kn** [comment]
Realizando

**Comment by leobuitrago** [comment]
Los parámetros **publishing_country=CO&country=CO** siempre deben estar presentes en el Query

**Comment by camiplata** [comment]
Se cierra el issue ya que en la versión actual del portal no se esta consumiendo información de GBIF
