### ISSUE TITLE
Estadísticas para las diferentes páginas

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/portal-de-datos-frontend#96]
Para diferentes páginas se requiere mostrar información contextual:

Home:
 * REGISTROS
 * CON COORDENADAS
 * ESPECIES

**Comment by jag2kn** [comment]
@leobuitrago 

Me puede ayudar a ver como gbif puede dar consultas de totales para diferentes consultas:

Para el home tenemos:

 * Registros (parece que funciona): https://api.gbif.org/v1/occurrence/search?limit=0&country=CO&publishingCountry=CO
 * Coordenadas (parece que funciona): https://api.gbif.org/v1/occurrence/search?limit=0&country=CO&publishingCountry=CO&hasCoordinate=true
 * Especies (no funciona): https://api.gbif.org/v1/species/search?limit=0&country=CO&publishingCountry=CO",

**Comment by jag2kn** [comment]
Recursos:
 * https://api.gbif.org/v1/occurrence/search?limit=0&country=CO&publishingCountry=CO&datasetKey=9850b85a-793f-429d-a437-2d5b46282acf
 * https://api.gbif.org/v1/occurrence/search?limit=0&country=CO&publishingCountry=CO&hasCoordinate=true&datasetKey=9850b85a-793f-429d-a437-2d5b46282acf
 * https://api.gbif.org/v1/species/search?limit=0&country=CO&publishingCountry=CO&datasetKey=9850b85a-793f-429d-a437-2d5b46282acf

Publicadores:
 * https://api.gbif.org/v1/occurrence/search?limit=0&country=CO&publishingCountry=CO&publishingOrganizationKey=b14a19b8-1288-40b2-88a7-758a63a772cf
 * https://api.gbif.org/v1/occurrence/search?limit=0&country=CO&publishingCountry=CO&hasCoordinate=true&publishingOrganizationKey=b14a19b8-1288-40b2-88a7-758a63a772cf
 * https://api.gbif.org/v1/species/search?limit=0&country=CO&publishingCountry=CO&publishingOrganizationKey=b14a19b8-1288-40b2-88a7-758a63a772cf

**Comment by jag2kn** [comment]
Se que algunos no están funcionando, la idea es tratar de ajustar los que no funcionan

**Comment by johnfra797** [comment]
Esto no lo comprendo

**Comment by camiplata** [comment]
Se cierra este issue, este tema se trata en detalle en el issue #166,
