### ISSUE TITLE
Marker para mapas

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#97]
Marker: 

PNG: 
![marker-12](https://user-images.githubusercontent.com/14220404/34228245-19d3bf18-e59e-11e7-855a-d1a8d559e655.png)

SVG: 
https://drive.google.com/file/d/1vxjeLS9UHDYGLTRbEr7QwoJxX8x8jniK/view?usp=sharing

**Comment by jag2kn** [comment]
Hecho
http://beta.datos.biodiversidad.co/occurrence/1065328658
