### ISSUE TITLE
Enlace -->Entérate cómo 

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal-de-datos-frontend#99]
debe ir a la página estática "sobre este portal" --> http://beta.datos.biodiversidad.co/static/sobre_el_portal

**Comment by camiplata** [comment]
El issue fue resuelto
@dapino el estilo de la página 'sobre este portal' cambia en cada canal:

![image](https://user-images.githubusercontent.com/5700527/42712513-9be6cec8-86b1-11e8-8e2d-e6c5b5aa0c28.png)

![image](https://user-images.githubusercontent.com/5700527/42712541-acdae106-86b1-11e8-8401-74f5c8074ae5.png)
